# Generated by Django 5.2.8 on 2025-12-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.CharField(unique=True, verbose_name='Путь к файлу на сервере'),
        ),
    ]
