# Generated by Django 6.0 on 2026-01-23 17:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: Spotify Premium, Netflix, Яндекс Плюс и т.д.', max_length=200, verbose_name='Название подписки')),
                ('price', models.DecimalField(decimal_places=2, help_text='Сумма регулярного платежа', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Стоимость')),
                ('currency', models.CharField(choices=[('RUB', '₽ Рубли'), ('USD', '$ Доллары США'), ('EUR', '€ Евро'), ('UAH', '₴ Гривны')], default='RUB', max_length=3, verbose_name='Валюта')),
                ('period', models.CharField(choices=[('monthly', 'Ежемесячно'), ('quarterly', 'Раз в 3 месяца'), ('semi_annual', 'Раз в полгода'), ('annual', 'Ежегодно'), ('one_time', 'Разовый платёж')], default='monthly', max_length=20, verbose_name='Периодичность')),
                ('next_payment_date', models.DateField(help_text='Когда ожидается следующий списание', verbose_name='Дата следующего платежа')),
                ('is_active', models.BooleanField(default=True, help_text='Отключена подписка или нет', verbose_name='Активна')),
                ('service_url', models.URLField(blank=True, help_text='Опционально: сайт или личный кабинет подписки', max_length=500, null=True, verbose_name='Ссылка на сервис')),
                ('note', models.TextField(blank=True, help_text='Например: семейный тариф, используется на 2 устройствах и т.д.', verbose_name='Заметка / комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'ordering': ['next_payment_date', 'name'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='pages_subsc_user_id_c23bbe_idx'), models.Index(fields=['next_payment_date'], name='pages_subsc_next_pa_c9d976_idx')],
            },
        ),
    ]
